package main

import (
	"fmt"
	"io"
	"sort"
)

// EmitConstants writes a Go source file with one exported rune constant per icon.
// Constants are output in lexicographic order by constant name.
func EmitConstants(w io.Writer, pkg string, entries []IconEntry) error {
	// Emit generated header.
	if _, err := fmt.Fprintf(w, "// Code generated by tools/gen-icons; DO NOT EDIT.\n"); err != nil {
		return err
	}

	// Emit package declaration.
	if _, err := fmt.Fprintf(w, "\npackage %s\n", pkg); err != nil {
		return err
	}

	// Build a slice of converted names paired with their codepoints.
	type constEntry struct {
		Name      string // PascalCase constant name (e.g. "IconWifi")
		Codepoint rune
	}
	consts := make([]constEntry, len(entries))
	for i, e := range entries {
		consts[i] = constEntry{
			Name:      SnakeToPascal(e.Name),
			Codepoint: e.Codepoint,
		}
	}

	// Sort by constant name lexicographically.
	sort.Slice(consts, func(i, j int) bool {
		return consts[i].Name < consts[j].Name
	})

	// Emit one const per entry.
	for _, c := range consts {
		if _, err := fmt.Fprintf(w, "\nconst %s rune = 0x%04X\n", c.Name, c.Codepoint); err != nil {
			return err
		}
	}

	return nil
}
