package codegen

import (
	"fmt"
	"io"
	"sort"
)

// EmitConfig holds all parameters needed to emit a generated Go source file.
type EmitConfig struct {
	PackageName  string
	FontID       string
	StructName   string
	ConstName    string
	ArrayName    string
	GlyphWidth   int
	GlyphHeight  int
	GlyphAdvance int
	RowHeight    int

	// GlyphMap holds the glyph data keyed by rune codepoint.
	// The emitter generates a map[rune][N]uint32 literal with map-lookup
	// GlyphRow dispatch and fallback character support.
	GlyphMap map[rune][]uint32

	// FallbackChar is rendered for unknown codepoints.
	// Defaults to '?' if zero.
	FallbackChar rune
}

// Emit writes a Go source file to w based on the given configuration.
// The output implements the font.Face interface and registers itself via init().
// It generates a map[rune][N]uint32 literal with map-lookup GlyphRow dispatch.
func Emit(w io.Writer, cfg EmitConfig) error {
	return emitMapBased(w, cfg)
}

// emitMapBased generates a map[rune][N]uint32 font source for glyph sets.
// The generated GlyphRow dispatches via map lookup with fallback character.
func emitMapBased(w io.Writer, cfg EmitConfig) error {
	fallback := cfg.FallbackChar
	if fallback == 0 {
		fallback = '?'
	}

	mapName := cfg.ArrayName + "Map"

	// Header: generated comment + package declaration.
	if _, err := fmt.Fprintf(w, "// Code generated by tools/fontgen; DO NOT EDIT.\n\npackage %s\n", cfg.PackageName); err != nil {
		return err
	}

	// Const for font ID.
	if _, err := fmt.Fprintf(w, "\nconst %s = %q\n", cfg.ConstName, cfg.FontID); err != nil {
		return err
	}

	// Const for fallback char (rune type for map lookup).
	if _, err := fmt.Fprintf(w, "\nconst %sFallback rune = %d\n", cfg.ArrayName, fallback); err != nil {
		return err
	}

	// Face struct type.
	if _, err := fmt.Fprintf(w, "\ntype %s struct{}\n", cfg.StructName); err != nil {
		return err
	}

	// ID() method.
	if _, err := fmt.Fprintf(w, "\nfunc (%s) ID() string { return %s }\n", cfg.StructName, cfg.ConstName); err != nil {
		return err
	}

	// Metrics() method.
	if _, err := fmt.Fprintf(w, "\nfunc (%s) Metrics() Metrics {\n", cfg.StructName); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "\treturn Metrics{GlyphWidth: %d, GlyphHeight: %d, GlyphAdvance: %d, RowHeight: %d}\n", cfg.GlyphWidth, cfg.GlyphHeight, cfg.GlyphAdvance, cfg.RowHeight); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "}\n"); err != nil {
		return err
	}

	// GlyphRow() method with map lookup and fallback.
	if _, err := fmt.Fprintf(w, "\nfunc (%s) GlyphRow(ch rune, row int) uint32 {\n", cfg.StructName); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "\tif row < 0 || row >= %d {\n\t\treturn 0\n\t}\n", cfg.GlyphHeight); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "\tif data, ok := %s[ch]; ok {\n\t\treturn data[row]\n\t}\n", mapName); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "\tif data, ok := %s[%sFallback]; ok {\n\t\treturn data[row]\n\t}\n", mapName, cfg.ArrayName); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "\treturn 0\n}\n"); err != nil {
		return err
	}

	// init() function.
	if _, err := fmt.Fprintf(w, "\nfunc init() {\n\tRegister(%s{})\n}\n", cfg.StructName); err != nil {
		return err
	}

	// Map literal: map[rune][N]uint32.
	// Sort runes for deterministic output.
	runes := make([]rune, 0, len(cfg.GlyphMap))
	for r := range cfg.GlyphMap {
		runes = append(runes, r)
	}
	sort.Slice(runes, func(i, j int) bool { return runes[i] < runes[j] })

	if _, err := fmt.Fprintf(w, "\nvar %s = map[rune][%d]uint32{\n", mapName, cfg.GlyphHeight); err != nil {
		return err
	}
	for _, r := range runes {
		if _, err := fmt.Fprintf(w, "\t%d: {", r); err != nil {
			return err
		}
		rows := cfg.GlyphMap[r]
		for i := 0; i < cfg.GlyphHeight; i++ {
			var val uint32
			if i < len(rows) {
				val = rows[i]
			}
			if i > 0 {
				if _, err := fmt.Fprint(w, ", "); err != nil {
					return err
				}
			}
			if _, err := fmt.Fprintf(w, "0x%08X", val); err != nil {
				return err
			}
		}
		if _, err := fmt.Fprintf(w, "}, // %q\n", string(r)); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(w, "}\n"); err != nil {
		return err
	}

	return nil
}
