package codegen

import (
	"bytes"
	"strings"
	"testing"
)

func TestEmitGeneratedHeader(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "spleen-5x8",
		StructName:   "spleen5x8Face",
		ConstName:    "Spleen5x8ID",
		ArrayName:    "spleen5x8Rows",
		GlyphWidth:   5,
		GlyphHeight:  8,
		GlyphAdvance: 6,
		RowHeight:    10,
		GlyphMap:     map[rune][]uint32{32: {0, 0, 0, 0, 0, 0, 0, 0}},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// The first line must be the generated comment.
	if !strings.HasPrefix(output, "// Code generated by tools/fontgen; DO NOT EDIT.\n") {
		t.Errorf("output does not start with generated comment:\n%s", output[:min(len(output), 100)])
	}
}

func TestEmitPackageDeclaration(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-1x1",
		StructName:   "test1x1Face",
		ConstName:    "Test1x1ID",
		ArrayName:    "test1x1Rows",
		GlyphWidth:   1,
		GlyphHeight:  1,
		GlyphAdvance: 2,
		RowHeight:    2,
		GlyphMap:     map[rune][]uint32{32: {0}},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "package font\n") {
		t.Errorf("output missing package declaration")
	}
}

func TestEmitConstAndType(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "spleen-6x12",
		StructName:   "spleen6x12Face",
		ConstName:    "Spleen6x12ID",
		ArrayName:    "spleen6x12Rows",
		GlyphWidth:   6,
		GlyphHeight:  12,
		GlyphAdvance: 7,
		RowHeight:    14,
		GlyphMap:     map[rune][]uint32{32: make([]uint32, 12)},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	if !strings.Contains(output, `const Spleen6x12ID = "spleen-6x12"`) {
		t.Error("missing const declaration")
	}
	if !strings.Contains(output, "type spleen6x12Face struct{}") {
		t.Error("missing struct type declaration")
	}
}

func TestEmitMethods(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "spleen-6x12",
		StructName:   "spleen6x12Face",
		ConstName:    "Spleen6x12ID",
		ArrayName:    "spleen6x12Rows",
		GlyphWidth:   6,
		GlyphHeight:  12,
		GlyphAdvance: 7,
		RowHeight:    14,
		GlyphMap:     map[rune][]uint32{32: make([]uint32, 12), '?': make([]uint32, 12)},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// ID method
	if !strings.Contains(output, "func (spleen6x12Face) ID() string { return Spleen6x12ID }") {
		t.Error("missing or incorrect ID() method")
	}

	// Metrics method
	if !strings.Contains(output, "return Metrics{GlyphWidth: 6, GlyphHeight: 12, GlyphAdvance: 7, RowHeight: 14}") {
		t.Error("missing or incorrect Metrics() return")
	}

	// GlyphRow bounds check
	if !strings.Contains(output, "if row < 0 || row >= 12 {") {
		t.Error("missing or incorrect row bounds check in GlyphRow()")
	}

	// Map lookup
	if !strings.Contains(output, "if data, ok := spleen6x12RowsMap[ch]; ok {") {
		t.Error("missing map lookup in GlyphRow()")
	}

	// Fallback lookup
	if !strings.Contains(output, "if data, ok := spleen6x12RowsMap[spleen6x12RowsFallback]; ok {") {
		t.Error("missing fallback lookup in GlyphRow()")
	}
}

func TestEmitInitRegister(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "spleen-6x12",
		StructName:   "spleen6x12Face",
		ConstName:    "Spleen6x12ID",
		ArrayName:    "spleen6x12Rows",
		GlyphWidth:   6,
		GlyphHeight:  12,
		GlyphAdvance: 7,
		RowHeight:    14,
		GlyphMap:     map[rune][]uint32{32: make([]uint32, 12)},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "func init() {\n\tRegister(spleen6x12Face{})\n}") {
		t.Error("missing or incorrect init() function")
	}
}

func TestEmitMapDeclaration(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-2x3",
		StructName:   "test2x3Face",
		ConstName:    "Test2x3ID",
		ArrayName:    "test2x3Rows",
		GlyphWidth:   2,
		GlyphHeight:  3,
		GlyphAdvance: 3,
		RowHeight:    4,
		GlyphMap: map[rune][]uint32{
			32: {0x00000000, 0x00000000, 0x00000000},
			33: {0x00000001, 0x00000002, 0x00000003},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// Map declaration with correct dimensions.
	if !strings.Contains(output, "var test2x3RowsMap = map[rune][3]uint32{") {
		t.Error("missing or incorrect map declaration")
	}

	// Verify hex formatting of glyph rows.
	if !strings.Contains(output, "\t33: {0x00000001, 0x00000002, 0x00000003},") {
		t.Errorf("glyph '!' row data not formatted correctly")
	}
}

func TestEmitIdempotent(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-4x5",
		StructName:   "test4x5Face",
		ConstName:    "Test4x5ID",
		ArrayName:    "test4x5Rows",
		GlyphWidth:   4,
		GlyphHeight:  5,
		GlyphAdvance: 5,
		RowHeight:    6,
		GlyphMap: map[rune][]uint32{
			32: {0, 0, 0, 0, 0},
			65: {0x0F, 0x10, 0x1F, 0x10, 0x0F},
		},
	}

	var buf1, buf2 bytes.Buffer
	if err := Emit(&buf1, cfg); err != nil {
		t.Fatalf("first Emit failed: %v", err)
	}
	if err := Emit(&buf2, cfg); err != nil {
		t.Fatalf("second Emit failed: %v", err)
	}

	if buf1.String() != buf2.String() {
		t.Error("two Emit calls produced different output (not idempotent)")
	}
}

func TestEmitGlyphsShortRows(t *testing.T) {
	// If a glyph has fewer rows than GlyphHeight, missing rows should be 0.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-1x4",
		StructName:   "test1x4Face",
		ConstName:    "Test1x4ID",
		ArrayName:    "test1x4Rows",
		GlyphWidth:   1,
		GlyphHeight:  4,
		GlyphAdvance: 2,
		RowHeight:    5,
		GlyphMap: map[rune][]uint32{
			// Only provide 2 rows — remaining should be zero-filled.
			32: {0x00000001, 0x00000002},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	// Should have 4 values with last 2 being zero.
	if !strings.Contains(output, "\t32: {0x00000001, 0x00000002, 0x00000000, 0x00000000},") {
		t.Errorf("short glyph rows not zero-padded correctly.\nGot:\n%s", output)
	}
}

func TestEmitFallbackCharConst(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-1x1",
		StructName:   "test1x1Face",
		ConstName:    "Test1x1ID",
		ArrayName:    "test1x1Rows",
		GlyphWidth:   1,
		GlyphHeight:  1,
		GlyphAdvance: 2,
		RowHeight:    2,
		GlyphMap:     map[rune][]uint32{32: {0}},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	// Default fallback is '?' (63).
	if !strings.Contains(output, "const test1x1RowsFallback rune = 63") {
		t.Errorf("missing fallback char const, got:\n%s", output)
	}
}

func TestEmitCustomFallbackChar(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-1x1",
		StructName:   "test1x1Face",
		ConstName:    "Test1x1ID",
		ArrayName:    "test1x1Rows",
		GlyphWidth:   1,
		GlyphHeight:  1,
		GlyphAdvance: 2,
		RowHeight:    2,
		GlyphMap:     map[rune][]uint32{32: {0}},
		FallbackChar: ' ',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	// Fallback is ' ' (32).
	if !strings.Contains(output, "const test1x1RowsFallback rune = 32") {
		t.Errorf("missing custom fallback char const, got:\n%s", output)
	}
}
