package codegen

import (
	"bytes"
	"strings"
	"testing"
)

func TestEmitMapBasedHeader(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "matrix-code",
		StructName:   "matrixcodeFace",
		ConstName:    "MatrixCodeID",
		ArrayName:    "matrixcodeRows",
		GlyphWidth:   7,
		GlyphHeight:  12,
		GlyphAdvance: 8,
		RowHeight:    14,
		GlyphMap: map[rune][]uint32{
			'A': {0x10, 0x28, 0x44, 0x82, 0xFE, 0x82, 0x82, 0x82, 0x00, 0x00, 0x00, 0x00},
			'B': {0xFC, 0x82, 0x82, 0xFC, 0x82, 0x82, 0x82, 0xFC, 0x00, 0x00, 0x00, 0x00},
		},
		FallbackChar: '?',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	if !strings.HasPrefix(output, "// Code generated by tools/fontgen; DO NOT EDIT.\n") {
		t.Errorf("output does not start with generated comment")
	}
	if !strings.Contains(output, "package font\n") {
		t.Errorf("output missing package declaration")
	}
}

func TestEmitMapBasedConstAndType(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "matrix-code",
		StructName:   "matrixcodeFace",
		ConstName:    "MatrixCodeID",
		ArrayName:    "matrixcodeRows",
		GlyphWidth:   7,
		GlyphHeight:  12,
		GlyphAdvance: 8,
		RowHeight:    14,
		GlyphMap: map[rune][]uint32{
			'A': {0x10, 0x28, 0x44, 0x82, 0xFE, 0x82, 0x82, 0x82, 0x00, 0x00, 0x00, 0x00},
		},
		FallbackChar: '?',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	if !strings.Contains(output, `const MatrixCodeID = "matrix-code"`) {
		t.Error("missing const declaration for font ID")
	}
	if !strings.Contains(output, `const matrixcodeRowsFallback rune = 63`) {
		t.Error("missing fallback char const")
	}
	if !strings.Contains(output, "type matrixcodeFace struct{}") {
		t.Error("missing struct type declaration")
	}
}

func TestEmitMapBasedMethods(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "matrix-code",
		StructName:   "matrixcodeFace",
		ConstName:    "MatrixCodeID",
		ArrayName:    "matrixcodeRows",
		GlyphWidth:   7,
		GlyphHeight:  12,
		GlyphAdvance: 8,
		RowHeight:    14,
		GlyphMap: map[rune][]uint32{
			'A': {0x10, 0x28, 0x44, 0x82, 0xFE, 0x82, 0x82, 0x82, 0x00, 0x00, 0x00, 0x00},
		},
		FallbackChar: '?',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// ID method.
	if !strings.Contains(output, "func (matrixcodeFace) ID() string { return MatrixCodeID }") {
		t.Error("missing or incorrect ID() method")
	}

	// Metrics method.
	if !strings.Contains(output, "return Metrics{GlyphWidth: 7, GlyphHeight: 12, GlyphAdvance: 8, RowHeight: 14}") {
		t.Error("missing or incorrect Metrics() return")
	}

	// GlyphRow row bounds check.
	if !strings.Contains(output, "if row < 0 || row >= 12 {") {
		t.Error("missing row bounds check in GlyphRow()")
	}

	// Map lookup.
	if !strings.Contains(output, "if data, ok := matrixcodeRowsMap[ch]; ok {") {
		t.Error("missing map lookup in GlyphRow()")
	}

	// Fallback lookup.
	if !strings.Contains(output, "if data, ok := matrixcodeRowsMap[matrixcodeRowsFallback]; ok {") {
		t.Error("missing fallback lookup in GlyphRow()")
	}

	// Final return 0.
	if !strings.Contains(output, "\treturn 0\n}") {
		t.Error("missing final return 0 in GlyphRow()")
	}
}

func TestEmitMapBasedInitRegister(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "matrix-code",
		StructName:   "matrixcodeFace",
		ConstName:    "MatrixCodeID",
		ArrayName:    "matrixcodeRows",
		GlyphWidth:   7,
		GlyphHeight:  12,
		GlyphAdvance: 8,
		RowHeight:    14,
		GlyphMap: map[rune][]uint32{
			'A': {0x10},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "func init() {\n\tRegister(matrixcodeFace{})\n}") {
		t.Error("missing or incorrect init() function")
	}
}

func TestEmitMapBasedMapDeclaration(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-map",
		StructName:   "testmapFace",
		ConstName:    "TestMapID",
		ArrayName:    "testmapRows",
		GlyphWidth:   4,
		GlyphHeight:  3,
		GlyphAdvance: 5,
		RowHeight:    4,
		GlyphMap: map[rune][]uint32{
			'A': {0x00000001, 0x00000002, 0x00000003},
			'B': {0x00000004, 0x00000005, 0x00000006},
		},
		FallbackChar: '?',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// Map declaration with correct dimensions.
	if !strings.Contains(output, "var testmapRowsMap = map[rune][3]uint32{") {
		t.Errorf("missing or incorrect map declaration.\nGot:\n%s", output)
	}

	// Verify hex formatting of glyph rows and rune key (A=65, B=66).
	if !strings.Contains(output, "65: {0x00000001, 0x00000002, 0x00000003},") {
		t.Errorf("glyph 'A' row data not formatted correctly.\nGot:\n%s", output)
	}
	if !strings.Contains(output, "66: {0x00000004, 0x00000005, 0x00000006},") {
		t.Errorf("glyph 'B' row data not formatted correctly.\nGot:\n%s", output)
	}
}

func TestEmitMapBasedSortedRunes(t *testing.T) {
	// Ensure that runes in the map are emitted in sorted order for determinism.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-sort",
		StructName:   "testsortFace",
		ConstName:    "TestSortID",
		ArrayName:    "testsortRows",
		GlyphWidth:   4,
		GlyphHeight:  2,
		GlyphAdvance: 5,
		RowHeight:    3,
		GlyphMap: map[rune][]uint32{
			'Z': {0x01, 0x02},
			'A': {0x03, 0x04},
			'M': {0x05, 0x06},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()

	// A=65, M=77, Z=90. They should appear in this order.
	posA := strings.Index(output, "65: {")
	posM := strings.Index(output, "77: {")
	posZ := strings.Index(output, "90: {")

	if posA < 0 || posM < 0 || posZ < 0 {
		t.Fatalf("not all rune entries found in output")
	}
	if !(posA < posM && posM < posZ) {
		t.Errorf("runes not emitted in sorted order: A@%d, M@%d, Z@%d", posA, posM, posZ)
	}
}

func TestEmitMapBasedDefaultFallback(t *testing.T) {
	// When FallbackChar is zero, it defaults to '?'.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-default-fb",
		StructName:   "testdefaultfbFace",
		ConstName:    "TestDefaultFbID",
		ArrayName:    "testdefaultfbRows",
		GlyphWidth:   4,
		GlyphHeight:  2,
		GlyphAdvance: 5,
		RowHeight:    3,
		GlyphMap: map[rune][]uint32{
			'?': {0xAA, 0xBB},
		},
		FallbackChar: 0, // should default to '?'
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, `const testdefaultfbRowsFallback rune = 63`) {
		t.Errorf("default fallback char not set to '?'.\nGot:\n%s", output)
	}
}

func TestEmitMapBasedCustomFallback(t *testing.T) {
	// Custom FallbackChar should be used.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-custom-fb",
		StructName:   "testcustomfbFace",
		ConstName:    "TestCustomFbID",
		ArrayName:    "testcustomfbRows",
		GlyphWidth:   4,
		GlyphHeight:  2,
		GlyphAdvance: 5,
		RowHeight:    3,
		GlyphMap: map[rune][]uint32{
			'*': {0xCC, 0xDD},
		},
		FallbackChar: '*',
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, `const testcustomfbRowsFallback rune = 42`) {
		t.Errorf("custom fallback char not emitted.\nGot:\n%s", output)
	}
}

func TestEmitMapBasedShortRows(t *testing.T) {
	// If a glyph has fewer rows than GlyphHeight, missing rows should be 0.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-short-map",
		StructName:   "testshortmapFace",
		ConstName:    "TestShortMapID",
		ArrayName:    "testshortmapRows",
		GlyphWidth:   4,
		GlyphHeight:  4,
		GlyphAdvance: 5,
		RowHeight:    5,
		GlyphMap: map[rune][]uint32{
			'X': {0x00000001, 0x00000002}, // Only 2 rows, should be zero-padded to 4
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	// Should have 4 values with last 2 being zero.
	if !strings.Contains(output, "88: {0x00000001, 0x00000002, 0x00000000, 0x00000000},") {
		t.Errorf("short glyph rows not zero-padded correctly.\nGot:\n%s", output)
	}
}

func TestEmitMapBasedIdempotent(t *testing.T) {
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-idem",
		StructName:   "testidemFace",
		ConstName:    "TestIdemID",
		ArrayName:    "testidemRows",
		GlyphWidth:   4,
		GlyphHeight:  3,
		GlyphAdvance: 5,
		RowHeight:    4,
		GlyphMap: map[rune][]uint32{
			'A':    {0x01, 0x02, 0x03},
			'Z':    {0x04, 0x05, 0x06},
			0xFF66: {0x07, 0x08, 0x09}, // Katakana half-width
		},
		FallbackChar: '?',
	}

	var buf1, buf2 bytes.Buffer
	if err := Emit(&buf1, cfg); err != nil {
		t.Fatalf("first Emit failed: %v", err)
	}
	if err := Emit(&buf2, cfg); err != nil {
		t.Fatalf("second Emit failed: %v", err)
	}

	if buf1.String() != buf2.String() {
		t.Error("two Emit calls produced different output (not idempotent)")
	}
}

func TestEmitMapBasedNoLegacyArrayGenerated(t *testing.T) {
	// When using GlyphMap path, the legacy [95][N]uint32 array should NOT appear.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-noarr",
		StructName:   "testnoarrFace",
		ConstName:    "TestNoarrID",
		ArrayName:    "testnoarrRows",
		GlyphWidth:   4,
		GlyphHeight:  2,
		GlyphAdvance: 5,
		RowHeight:    3,
		GlyphMap: map[rune][]uint32{
			'A': {0x01, 0x02},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if strings.Contains(output, "[95][") {
		t.Errorf("map-based emit path should not generate legacy [95] array.\nGot:\n%s", output)
	}
	if strings.Contains(output, "ch - 32") {
		t.Errorf("map-based emit path should not use 'ch - 32' indexing.\nGot:\n%s", output)
	}
}

func TestEmitMapBasedNilGlyphMapEmitsEmptyMap(t *testing.T) {
	// When GlyphMap is nil, the emitter still produces valid map-based output
	// (with an empty map).
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-nilmap",
		StructName:   "testnilmapFace",
		ConstName:    "TestNilmapID",
		ArrayName:    "testnilmapRows",
		GlyphWidth:   5,
		GlyphHeight:  8,
		GlyphAdvance: 6,
		RowHeight:    10,
		GlyphMap:     nil, // Nil GlyphMap produces an empty map literal
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	if !strings.Contains(output, "var testnilmapRowsMap = map[rune][8]uint32{") {
		t.Error("nil GlyphMap should still produce map-based output")
	}
	// Should NOT contain legacy array syntax.
	if strings.Contains(output, "[95][") {
		t.Error("nil GlyphMap should not produce legacy [95] array")
	}
}

func TestEmitMapBasedUnicodeComment(t *testing.T) {
	// Verify that rune comments are generated for readability.
	cfg := EmitConfig{
		PackageName:  "font",
		FontID:       "test-comment",
		StructName:   "testcommentFace",
		ConstName:    "TestCommentID",
		ArrayName:    "testcommentRows",
		GlyphWidth:   4,
		GlyphHeight:  2,
		GlyphAdvance: 5,
		RowHeight:    3,
		GlyphMap: map[rune][]uint32{
			'A': {0x01, 0x02},
		},
	}

	var buf bytes.Buffer
	if err := Emit(&buf, cfg); err != nil {
		t.Fatalf("Emit failed: %v", err)
	}

	output := buf.String()
	// The comment should contain the rune character.
	if !strings.Contains(output, `// "A"`) {
		t.Errorf("missing rune comment for 'A'.\nGot:\n%s", output)
	}
}
