package attract_hacking

// Fake data stream lines.
var hackinglines = []string{
	"> auth bypass // bridge.live.sentinel",
	"> decrypt /tmp/ghost.bin :: keyring.scan",
	"> relay :: 10.27.0.5 -> 188.24.9.12",
	"> exfiltrate :: shadowcache ./evidence/",
	"> inject payload :: neon-0x7F :: status=ready",
	"> obfuscate :: /dev/eye :: pulse confirmed",
	"> tunnel stable :: transfer 8.1k/s",
	"> echo // access granted // ghost-shell online",
	"> scan //firewall :: 3 ports open :: 2 closed",
	"> override // root access :: 0x7F::0xFF",
	"> upload // payload :: neon-0x7F :: status=active",
	"> monitor // network traffic :: 1.2k/s",
	"> exfiltrate // data :: shadowcache ./evidence/",
	"> inject // malware :: neon-0x7F :: status=ready",
	"> obfuscate // /dev/eye :: pulse confirmed",
	"> tunnel stable // transfer 8.1k/s",
	"> echo // access granted // ghost-shell online",
	"> scan //firewall :: 3 ports open :: 2 closed",
	"> override // root access :: 0x7F::0xFF",
	"> upload // payload :: neon-0x7F :: status=active",
	"> monitor // network traffic :: 1.2k/s",
	"> exfiltrate // data :: shadowcache ./evidence/",
	"> inject // malware :: neon-0x7F :: status=ready",
	"> obfuscate // /dev/eye :: pulse confirmed",
	"> tunnel stable // transfer 8.1k/s",
	"> echo // access granted // ghost-shell online",
	"> scan //firewall :: 3 ports open :: 2 closed",
	"> override // root access :: 0x7F::0xFF",
	"> upload // payload :: neon-0x7F :: status=active",
	"> monitor // network traffic :: 1.2k/s",
}
