package main

import (
	"bytes"
	"strings"
	"testing"

	"github.com/databeast/cyberhud/buildtools/fontgen/bdf"
	"github.com/databeast/cyberhud/buildtools/fontgen/codegen"
)

// Minimal Spleen 5×8-style BDF content with space and 'A' characters.
const testBDFSpleen5x8 = `STARTFONT 2.1
FONT -Misc-Spleen-Medium-R-Normal--8-80-72-72-C-50-ISO10646-1
SIZE 8 72 72
FONTBOUNDINGBOX 5 8 0 -1
STARTCHAR space
ENCODING 32
DWIDTH 5 0
BBX 5 8 0 0
BITMAP
00
00
00
00
00
00
00
00
ENDCHAR
STARTCHAR A
ENCODING 65
DWIDTH 5 0
BBX 5 8 0 0
BITMAP
0E
11
11
1F
11
11
11
00
ENDCHAR
ENDFONT
`

// TestFullPipelineSpleen5x8 tests the full BDF parse → codegen emit pipeline
// end-to-end using a minimal Spleen 5×8 BDF fixture.
//

func TestFullPipelineSpleen5x8(t *testing.T) {
	// Step 1: Parse the BDF file.
	font, err := bdf.Parse(strings.NewReader(testBDFSpleen5x8))
	if err != nil {
		t.Fatalf("bdf.Parse failed: %v", err)
	}

	// Verify we got the expected glyphs.
	if len(font.Glyphs) != 2 {
		t.Fatalf("expected 2 glyphs (space + A), got %d", len(font.Glyphs))
	}
	if _, ok := font.Glyphs[32]; !ok {
		t.Fatal("missing space glyph (codepoint 32)")
	}
	if _, ok := font.Glyphs[65]; !ok {
		t.Fatal("missing 'A' glyph (codepoint 65)")
	}

	// Step 2: Build glyph map for map-based emitter.
	const glyphHeight = 8
	glyphMap := make(map[rune][]uint32, len(font.Glyphs))
	for cp, g := range font.Glyphs {
		glyphMap[cp] = g.Rows
	}

	// Step 3: Emit the Go source.
	cfg := codegen.EmitConfig{
		PackageName:  "font",
		FontID:       "spleen-5x8",
		StructName:   "spleen5x8Face",
		ConstName:    "Spleen5x8ID",
		ArrayName:    "spleen5x8Rows",
		GlyphWidth:   5,
		GlyphHeight:  glyphHeight,
		GlyphAdvance: 6,
		RowHeight:    10,
		GlyphMap:     glyphMap,
	}

	var buf bytes.Buffer
	if err := codegen.Emit(&buf, cfg); err != nil {
		t.Fatalf("codegen.Emit failed: %v", err)
	}

	output := buf.String()

	// Step 4: Verify output contents.
	t.Run("header_comment", func(t *testing.T) {
		if !strings.Contains(output, "// Code generated by tools/fontgen; DO NOT EDIT.") {
			t.Error("output missing required generated file header comment")
		}
	})

	t.Run("package_declaration", func(t *testing.T) {
		if !strings.Contains(output, "package font") {
			t.Error("output missing 'package font' declaration")
		}
	})

	t.Run("const_declaration", func(t *testing.T) {
		if !strings.Contains(output, `const Spleen5x8ID = "spleen-5x8"`) {
			t.Error("output missing const Spleen5x8ID declaration")
		}
	})

	t.Run("face_struct", func(t *testing.T) {
		if !strings.Contains(output, "type spleen5x8Face struct{}") {
			t.Error("output missing spleen5x8Face struct declaration")
		}
	})

	t.Run("id_method", func(t *testing.T) {
		if !strings.Contains(output, "func (spleen5x8Face) ID() string { return Spleen5x8ID }") {
			t.Error("output missing ID() method")
		}
	})

	t.Run("metrics_method", func(t *testing.T) {
		if !strings.Contains(output, "GlyphWidth: 5") {
			t.Error("output missing GlyphWidth in Metrics()")
		}
		if !strings.Contains(output, "GlyphHeight: 8") {
			t.Error("output missing GlyphHeight in Metrics()")
		}
		if !strings.Contains(output, "GlyphAdvance: 6") {
			t.Error("output missing GlyphAdvance in Metrics()")
		}
		if !strings.Contains(output, "RowHeight: 10") {
			t.Error("output missing RowHeight in Metrics()")
		}
	})

	t.Run("glyphrow_bounds_check", func(t *testing.T) {
		// GlyphRow should check row bounds against height=8.
		if !strings.Contains(output, "row >= 8") {
			t.Error("output missing GlyphRow bounds check for height 8")
		}
	})

	t.Run("glyphrow_map_lookup", func(t *testing.T) {
		if !strings.Contains(output, "spleen5x8RowsMap[ch]") {
			t.Error("output missing map lookup in GlyphRow()")
		}
		if !strings.Contains(output, "spleen5x8RowsMap[spleen5x8RowsFallback]") {
			t.Error("output missing fallback lookup in GlyphRow()")
		}
	})

	t.Run("init_register", func(t *testing.T) {
		if !strings.Contains(output, "func init()") {
			t.Error("output missing init() function")
		}
		if !strings.Contains(output, "Register(spleen5x8Face{})") {
			t.Error("output missing Register call in init()")
		}
	})

	t.Run("map_declaration", func(t *testing.T) {
		if !strings.Contains(output, "var spleen5x8RowsMap = map[rune][8]uint32{") {
			t.Error("output missing glyph row map declaration")
		}
	})

	t.Run("glyph_row_values", func(t *testing.T) {
		// Verify 'A' glyph row values match expected hex conversions.
		// BDF hex "0E" → 0x0E → shifted left by (32-8)=24 bits → 0x0E000000
		// BDF hex "11" → 0x11 → shifted left by 24 bits → 0x11000000
		// BDF hex "1F" → 0x1F → shifted left by 24 bits → 0x1F000000

		expectedRows := []uint32{
			0x0E000000, // row 0: 0E
			0x11000000, // row 1: 11
			0x11000000, // row 2: 11
			0x1F000000, // row 3: 1F
			0x11000000, // row 4: 11
			0x11000000, // row 5: 11
			0x11000000, // row 6: 11
			0x00000000, // row 7: 00
		}

		// Verify parsed glyph 'A' matches expected values.
		glyphA := font.Glyphs[65]
		if len(glyphA.Rows) != 8 {
			t.Fatalf("glyph 'A' expected 8 rows, got %d", len(glyphA.Rows))
		}
		for i, expected := range expectedRows {
			if glyphA.Rows[i] != expected {
				t.Errorf("glyph 'A' row %d: got 0x%08X, want 0x%08X", i, glyphA.Rows[i], expected)
			}
		}

		// Verify the emitted output contains the correct hex values for glyph 'A'.
		if !strings.Contains(output, "0x0E000000") {
			t.Error("output missing expected 0x0E000000 value for glyph 'A'")
		}
		if !strings.Contains(output, "0x1F000000") {
			t.Error("output missing expected 0x1F000000 value for glyph 'A'")
		}
		if !strings.Contains(output, "0x11000000") {
			t.Error("output missing expected 0x11000000 value for glyph 'A'")
		}
	})

	t.Run("space_glyph_all_zeros", func(t *testing.T) {
		// Space (codepoint 32) should have all zero rows.
		glyphSpace := font.Glyphs[32]
		for i, row := range glyphSpace.Rows {
			if row != 0 {
				t.Errorf("space glyph row %d: got 0x%08X, want 0x00000000", i, row)
			}
		}
	})
}
